import { ThemeConfig } from "antd";

export const themeConfig: ThemeConfig = {
  token: {
    // borderRadius: "",
    colorBgBase: "#202024",
    colorBgContainer: "#323238",
    colorWhite: "#FFF",
    colorError: "",
    colorInfo: "",
    colorLink: "",
    colorPrimary: "#00875F",
    // colorSuccess: "",
    // colorTextBase: "",
    colorWarning: "#F75A68",
    // controlHeight: "",
    // fontFamily: "",
    // fontFamilyCode: "",
    // fontSize: "",
    // lineType: "",
    // lineWidth: "",
    // motion: "",
    // motionBase: "",
    // motionEaseInBack: "",
    // motionEaseInOut: "",
    // motionEaseInOutCirc: "",
    // motionEaseInQuint: "",
    // motionEaseOut: "",
    // motionEaseOutBack: "",
    // motionEaseOutCirc: "",
    // motionEaseOutQuint: "",
    // motionUnit: "",
    // opacityImage: "",
    // sizePopupArrow: "",
    // sizeStep: "",
    // sizeUnit: "",
    // wireframe: "",
    // zIndexBase: "",
    // zIndexPopupBase: ""
  },
  components: {
    Layout: {
      siderBg: "#121214",
      triggerBg: "#121214",
      headerBg: "#121214",
    },
    Menu: {
      itemBg: "#121214",
      itemColor: "#FFF",
      itemHoverBg: "#00875F",
      itemSelectedBg: "#00875F",
      itemSelectedColor: "#FFF",
      itemHoverColor: "#FFF",
    },
    Breadcrumb: {
      itemColor: "#FFF",
      lastItemColor: "#FFF",
      separatorColor: "#FFF",
    },
  }
}
